name: CI/CD C++ Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Configure and build BlackSquare
      run: |
        cmake -S . -B build/BlackSquare
        cmake --build build/BlackSquare
    
    - name: Configure and build Divisions
      run: |
        cmake -S . -B build/Divisions
        cmake --build build/Divisions
    
    - name: Configure and build Lucky
      run: |
        cmake -S . -B build/Lucky
        cmake --build build/Lucky
    
    - name: Configure and build YesOrYes
      run: |
        cmake -S . -B build/YesOrYes
        cmake --build build/YesOrYes

  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Code Quality tools (e.g., Clang, CPPCheck)
      run: |
        sudo apt-get install -y clang cppcheck

    - name: Run Code Quality Analysis for BlackSquare
      run: cppcheck BlackSquare.cpp
    
    - name: Run Code Quality Analysis for Divisions
      run: cppcheck Divisions.cpp
    
    - name: Run Code Quality Analysis for Lucky
      run: cppcheck Lucky.cpp
    
    - name: Run Code Quality Analysis for YesOrYes
      run: cppcheck YesOrYes.cpp

  artifact-repository:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: project-artifacts
        path: problem_sets
